# Domain Docs

How the engineering skills should consume this repo's domain documentation when
exploring the codebase.

This repo uses `.agentic-scaffold/BUSINESS_LOGIC.md` as the primary project brain, with `.agentic-scaffold/docs/`
and `.agentic-scaffold/docs/adr/` as supporting tracked documentation.

Agents must read `.agentic-scaffold/BUSINESS_LOGIC.md` first before planning, coding, or creating
issues. Future task plans must cite the relevant `.agentic-scaffold/BUSINESS_LOGIC.md` section.

`CONTEXT.md` remains a **verbatim mirror** of the Obsidian vault, regenerated by
`.agentic-scaffold/scripts/sync-context.sh`. Never hand-edit it. Do not read it whole. Use
`.agentic-scaffold/docs/context/INDEX.md` to map your work area to relevant sections.

When `CONTEXT.md` conflicts with `.agentic-scaffold/BUSINESS_LOGIC.md` or an accepted ADR, follow
`.agentic-scaffold/BUSINESS_LOGIC.md` and the accepted ADR. Treat `CONTEXT.md` as historical input
until the vault mirror is regenerated.

Glossary terms live in `.agentic-scaffold/docs/context/glossary.md`.

## Before exploring, read these

- **`.agentic-scaffold/BUSINESS_LOGIC.md`** — product fundamentals and non-negotiable rules.
- **`.agentic-scaffold/docs/context/INDEX.md`** — pick relevant historical `CONTEXT.md` sections.
- **`CONTEXT.md`** — only the sections the index points you to.
- **`.agentic-scaffold/docs/adr/`** — read ADRs that touch the area you're about to work in.

If any of these files don't exist, **proceed silently**. Don't flag their
absence; don't suggest creating them upfront.

## File structure

```
/
├── CONTEXT.md
├── AGENTS.md -> .agentic-scaffold/AGENTS.md
├── CLAUDE.md -> .agentic-scaffold/CLAUDE.md
└── .agentic-scaffold/
    ├── BUSINESS_LOGIC.md
    ├── docs/adr/
    │   ├── 0001-example-decision.md
    │   └── 0002-another-decision.md
    └── ...
```

## Use the glossary's vocabulary

When your output names a domain concept, use the term as defined in
`.agentic-scaffold/docs/context/glossary.md`. Don't drift to synonyms the glossary explicitly
avoids.

If the concept you need isn't in the glossary yet, that's a signal — either
you're inventing language the project doesn't use (reconsider) or there's a
real gap (note it).

## Flag ADR conflicts

If your output contradicts an existing ADR, surface it explicitly rather than
silently overriding:

> _Contradicts ADR-XXXX — but worth reopening because…_
